In [1]:
import numpy as np

In [2]:
vetor = [1, 5, 9]

In [10]:
type(vetor)

list

In [11]:
meuvetor = np.array(vetor)

In [12]:
meuvetor

array([1, 5, 9])

In [13]:
type(meuvetor)

numpy.ndarray

In [17]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
np.zeros(shape=(4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(shape=(5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
type(0)

int

In [26]:
type(0.)

float