In [1]:
import numpy as np

In [2]:
np.random.seed(101)
vetor = np.random.randint(0,100,10)

In [4]:
vetor.shape

(10,)

In [5]:
vetor

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [6]:
vetor.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [7]:
vetor.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])